// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx72mzyEpXN5HSZYOi_QsG26OlNxmArcI',
    appId: '1:32518278088:web:7e6abeec077a3d94308efd',
    messagingSenderId: '32518278088',
    projectId: 'glamcodeflutter',
    authDomain: 'glamcodeflutter.firebaseapp.com',
    storageBucket: 'glamcodeflutter.appspot.com',
    measurementId: 'G-T0WKWWCG87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhkMkZRsfmIezAuQOePphi9Xd8DlZfQU',
    appId: '1:32518278088:android:ef0dc2464aaf839c308efd',
    messagingSenderId: '32518278088',
    projectId: 'glamcodeflutter',
    storageBucket: 'glamcodeflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hZsKyj6zbXdOJN0ZEOKfj3dXNPyvfDU',
    appId: '1:32518278088:ios:f51a67bab92d9e7d308efd',
    messagingSenderId: '32518278088',
    projectId: 'glamcodeflutter',
    storageBucket: 'glamcodeflutter.appspot.com',
    androidClientId: '32518278088-5dg337nhqaf9salnj6o43k78j1fujr2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautician',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hZsKyj6zbXdOJN0ZEOKfj3dXNPyvfDU',
    appId: '1:32518278088:ios:b400a6c326ed581f308efd',
    messagingSenderId: '32518278088',
    projectId: 'glamcodeflutter',
    storageBucket: 'glamcodeflutter.appspot.com',
    androidClientId: '32518278088-5dg337nhqaf9salnj6o43k78j1fujr2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautician.RunnerTests',
  );
}
